using AiTradingRace.Functions.Models;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Extensions.Logging;

namespace AiTradingRace.Functions.Activities;

/// <summary>
/// Activity function to execute trades from agent decisions.
/// This activity processes the orders generated by agent decisions.
/// </summary>
public sealed class ExecuteTradesActivity
{
    private readonly ILogger<ExecuteTradesActivity> _logger;

    public ExecuteTradesActivity(ILogger<ExecuteTradesActivity> logger)
    {
        _logger = logger;
    }

    [Function(nameof(ExecuteTradesActivity))]
    public Task<int> Run(
        [ActivityTrigger] ExecuteTradesRequest request,
        CancellationToken ct)
    {
        // Note: Orders are already executed within the AgentRunner.RunAgentOnceAsync call.
        // This activity is for any post-processing or additional trade execution logic.
        // Currently it just counts the successful trades for reporting.

        var successfulDecisions = request.Decisions
            .Where(d => d.Success)
            .ToList();

        var totalOrders = successfulDecisions
            .Sum(d => d.Decision.Orders.Count);

        _logger.LogInformation(
            "Executed {OrderCount} orders from {AgentCount} agents at {Timestamp}",
            totalOrders, successfulDecisions.Count, request.Timestamp);

        return Task.FromResult(totalOrders);
    }
}
