// <auto-generated />
using System;
using AiTradingRace.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AiTradingRace.Infrastructure.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    [Migration("20260116213433_AddEquitySnapshotCashPositionValues")]
    partial class AddEquitySnapshotCashPositionValues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("AiTradingRace.Domain.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Agents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 16, 21, 34, 33, 371, DateTimeKind.Unspecified).AddTicks(9730), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "GPT",
                            Provider = "AzureOpenAI"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 16, 21, 34, 33, 371, DateTimeKind.Unspecified).AddTicks(9730), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Claude",
                            Provider = "Anthropic"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 16, 21, 34, 33, 371, DateTimeKind.Unspecified).AddTicks(9730), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Grok",
                            Provider = "xAI"
                        });
                });

            modelBuilder.Entity("AiTradingRace.Domain.Entities.EquitySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CashValue")
                        .HasColumnType("decimal(18,8)");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PositionsValue")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("UnrealizedPnL")
                        .HasColumnType("decimal(18,8)");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId", "CapturedAt");

                    b.ToTable("EquitySnapshots", (string)null);
                });

            modelBuilder.Entity("AiTradingRace.Domain.Entities.MarketAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuoteCurrency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("MarketAssets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3d4b060-55bb-4e48-8f04-3452ec0c9d4c"),
                            ExternalId = "bitcoin",
                            IsEnabled = true,
                            Name = "Bitcoin",
                            QuoteCurrency = "USD",
                            Symbol = "BTC"
                        },
                        new
                        {
                            Id = new Guid("b1fa9f8a-626b-4253-9a5d-0c9c9fb5c9fd"),
                            ExternalId = "ethereum",
                            IsEnabled = true,
                            Name = "Ethereum",
                            QuoteCurrency = "USD",
                            Symbol = "ETH"
                        });
                });

            modelBuilder.Entity("AiTradingRace.Domain.Entities.MarketCandle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(18,8)");

                    b.Property<Guid>("MarketAssetId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(18,8)");

                    b.HasKey("Id");

                    b.HasIndex("MarketAssetId", "TimestampUtc")
                        .IsUnique();

                    b.ToTable("MarketCandles", null, t =>
                        {
                            t.HasCheckConstraint("CK_MarketCandle_PricesPositive", "[Open] > 0 AND [High] > 0 AND [Low] > 0 AND [Close] > 0");

                            t.HasCheckConstraint("CK_MarketCandle_VolumeNonNegative", "[Volume] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Close = 47200m,
                            High = 47500m,
                            Low = 46500m,
                            MarketAssetId = new Guid("c3d4b060-55bb-4e48-8f04-3452ec0c9d4c"),
                            Open = 47000m,
                            TimestampUtc = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Volume = 1250m
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Close = 3235m,
                            High = 3250m,
                            Low = 3150m,
                            MarketAssetId = new Guid("b1fa9f8a-626b-4253-9a5d-0c9c9fb5c9fd"),
                            Open = 3200m,
                            TimestampUtc = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Volume = 8500m
                        });
                });

            modelBuilder.Entity("AiTradingRace.Domain.Entities.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("USD");

                    b.Property<decimal>("Cash")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,8)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("AgentId")
                        .IsUnique();

                    b.ToTable("Portfolios", null, t =>
                        {
                            t.HasCheckConstraint("CK_Portfolio_Cash_NonNegative", "[Cash] >= 0");
                        });
                });

            modelBuilder.Entity("AiTradingRace.Domain.Entities.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AverageEntryPrice")
                        .HasColumnType("decimal(18,8)");

                    b.Property<Guid>("MarketAssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,8)");

                    b.HasKey("Id");

                    b.HasIndex("MarketAssetId");

                    b.HasIndex("PortfolioId", "MarketAssetId")
                        .IsUnique();

                    b.ToTable("Positions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Position_AverageEntryPrice_NonNegative", "[AverageEntryPrice] >= 0");

                            t.HasCheckConstraint("CK_Position_Quantity_NonNegative", "[Quantity] >= 0");
                        });
                });

            modelBuilder.Entity("AiTradingRace.Domain.Entities.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MarketAssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,8)");

                    b.Property<int>("Side")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MarketAssetId");

                    b.HasIndex("PortfolioId");

                    b.ToTable("Trades", null, t =>
                        {
                            t.HasCheckConstraint("CK_Trade_Price_Positive", "[Price] > 0");

                            t.HasCheckConstraint("CK_Trade_Quantity_Positive", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("AiTradingRace.Domain.Entities.EquitySnapshot", b =>
                {
                    b.HasOne("AiTradingRace.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("AiTradingRace.Domain.Entities.MarketCandle", b =>
                {
                    b.HasOne("AiTradingRace.Domain.Entities.MarketAsset", null)
                        .WithMany()
                        .HasForeignKey("MarketAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiTradingRace.Domain.Entities.Portfolio", b =>
                {
                    b.HasOne("AiTradingRace.Domain.Entities.Agent", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiTradingRace.Domain.Entities.Position", b =>
                {
                    b.HasOne("AiTradingRace.Domain.Entities.MarketAsset", null)
                        .WithMany()
                        .HasForeignKey("MarketAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiTradingRace.Domain.Entities.Portfolio", null)
                        .WithMany("Positions")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiTradingRace.Domain.Entities.Trade", b =>
                {
                    b.HasOne("AiTradingRace.Domain.Entities.MarketAsset", "MarketAsset")
                        .WithMany()
                        .HasForeignKey("MarketAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AiTradingRace.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketAsset");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("AiTradingRace.Domain.Entities.Portfolio", b =>
                {
                    b.Navigation("Positions");
                });
#pragma warning restore 612, 618
        }
    }
}
